CREATE DATABASE projeto1;
USE projeto1;


CREATE TABLE VENDEDORES (
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    JANEIRO FLOAT(10,2),
    FEVEREIRO FLOAT(10,2),
    MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES(NULL, 'CARLOS', 'M', 373773.38, 55353.33, 36363.77);
INSERT INTO VENDEDORES VALUES(NULL, 'ANA', 'F', 420000.50, 65000.00, 41000.50);
INSERT INTO VENDEDORES VALUES(NULL, 'MARCELO', 'M', 280000.75, 35000.25, 30000.00);
INSERT INTO VENDEDORES VALUES(NULL, 'JULIANA', 'F', 500000.00, 85000.40, 42000.80);
INSERT INTO VENDEDORES VALUES(NULL, 'FERNANDO', 'M', 320000.25, 45000.10, 38000.60);
INSERT INTO VENDEDORES VALUES(NULL, 'LUCAS', 'M', 600000.00, 90000.00, 50000.00);
INSERT INTO VENDEDORES VALUES(NULL, 'ISABELA', 'F', 400000.00, 70000.50, 39000.10);
INSERT INTO VENDEDORES VALUES(NULL, 'RICARDO', 'M', 330000.75, 40000.30, 33000.00);
INSERT INTO VENDEDORES VALUES(NULL, 'PAULA', 'F', 470000.00, 78000.10, 42000.90);
INSERT INTO VENDEDORES VALUES(NULL, 'JOSÉ', 'M', 350000.00, 60000.75, 36000.50);
INSERT INTO VENDEDORES VALUES(NULL, 'MARINA', 'F', 460000.00, 80000.00, 41000.00);

----------- SELECTS -------------

SELECT MAX(FEVEREIRO) AS MAIOR_FEV FROM VENDEDORES;
SELECT MIN(FEVEREIRO) AS MENOR_FEV FROM VENDEDORES;
SELECT AVG(FEVEREIRO) AS MEDIA_FEV FROM VENDEDORES;


SELECT 
    MAX(JANEIRO) AS MAX_JAN,
    MIN(JANEIRO) AS MIN_JAN,
    AVG(JANEIRO) AS AVG_JAN,
    MAX(FEVEREIRO) AS MAX_FEV,
    MIN(FEVEREIRO) AS MIN_FEV,
    AVG(FEVEREIRO) AS AVG_FEV,
    MAX(MARCO) AS MAX_MAR,
    MIN(MARCO) AS MIN_MAR,
    AVG(MARCO) AS AVG_MAR
FROM VENDEDORES;


SELECT 
    MAX(JANEIRO) AS MAX_JAN,
    MIN(JANEIRO) AS MIN_JAN,
    TRUNCATE(AVG(JANEIRO), 2) AS AVG_JAN
FROM VENDEDORES;


SELECT SUM(JANEIRO) AS TOTAL_JAN FROM VENDEDORES;
SELECT 
    SUM(JANEIRO) AS TOTAL_JAN,
    SUM(FEVEREIRO) AS TOTAL_FEV,
    SUM(MARCO) AS TOTAL_MAR
FROM VENDEDORES;


SELECT SEXO, SUM(JANEIRO) AS TOTAL_JAN
FROM VENDEDORES
GROUP BY SEXO;


SELECT NOME, MARCO 
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);


SELECT NOME, MARCO 
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);


SELECT NOME, FEVEREIRO 
FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);


SELECT AVG(FEVEREIRO) AS MEDIA_FEV FROM VENDEDORES;


SELECT 
    NOME,
    JANEIRO,
    FEVEREIRO,
    MARCO,
    (JANEIRO + FEVEREIRO + MARCO) AS TOTAL,
    TRUNCATE((JANEIRO + FEVEREIRO + MARCO) / 3, 2) AS MEDIA
FROM VENDEDORES;


SELECT 
    NOME,
    JANEIRO,
    FEVEREIRO,
    MARCO,
    (JANEIRO + FEVEREIRO + MARCO) AS TOTAL,
    (JANEIRO + FEVEREIRO + MARCO) * 0.25 AS BONUS_25_PORCENTO,
    TRUNCATE((JANEIRO + FEVEREIRO + MARCO) / 3, 2) AS MEDIA
FROM VENDEDORES;
