CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE PACIENTE (
    IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    DATA_NASC DATE NOT NULL
);

CREATE TABLE TELEFONE (
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL','RES','COM') NOT NULL,
    NUMERO VARCHAR(15) NOT NULL,
    ID_PACIENTE INT
);

CREATE TABLE MEDICO (
    IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CRM VARCHAR(20) UNIQUE NOT NULL,
    ID_ESPECIALIDADE INT
);

CREATE TABLE ESPECIALIDADE (
    IDESPECIALIDADE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE SALA (
    IDSALA INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO VARCHAR(10) UNIQUE,
    TIPO ENUM('CONSULTA', 'CIRURGIA', 'EXAME')
);

CREATE TABLE ATENDIMENTO (
    IDATENDIMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE INT,
    ID_MEDICO INT,
    DATA_ATENDIMENTO DATE,
    IDSALA INT
);


ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TEL_PAC
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE MEDICO
ADD CONSTRAINT FK_MED_ESPEC
FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(IDESPECIALIDADE);

ALTER TABLE ATENDIMENTO
ADD CONSTRAINT FK_AT_PAC
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE ATENDIMENTO
ADD CONSTRAINT FK_AT_MED
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE ATENDIMENTO
ADD CONSTRAINT FK_AT_SALA
FOREIGN KEY (IDSALA) REFERENCES SALA(IDSALA);

----------- SELECTS--------

SELECT 
    P.NOME AS PACIENTE,
    M.NOME AS MEDICO,
    E.NOME AS ESPECIALIDADE,
    A.DATA_ATENDIMENTO
FROM 
    ATENDIMENTO A
JOIN 
    PACIENTE P ON A.ID_PACIENTE = P.IDPACIENTE
JOIN 
    MEDICO M ON A.ID_MEDICO = M.IDMEDICO
JOIN 
    ESPECIALIDADE E ON M.ID_ESPECIALIDADE = E.IDESPECIALIDADE;


SELECT 
    S.NUMERO,
    COUNT(A.IDATENDIMENTO) AS QTD_ATENDIMENTOS
FROM 
    SALA S
LEFT JOIN 
    ATENDIMENTO A ON S.IDSALA = A.IDSALA
GROUP BY 
    S.NUMERO;


SELECT 
    P.NOME
FROM 
    PACIENTE P
WHERE 
    P.IDPACIENTE NOT IN (
        SELECT ID_PACIENTE FROM ATENDIMENTO
    );

------- DELETES --------

DELETE FROM TELEFONE
WHERE TIPO = 'COM';

DELETE FROM PACIENTE
WHERE IDPACIENTE NOT IN (
    SELECT DISTINCT ID_PACIENTE FROM ATENDIMENTO
);

-------- ALTER TABLE'S ------------

ALTER TABLE PACIENTE
ADD CPF VARCHAR(14) UNIQUE;

ALTER TABLE TELEFONE
MODIFY NUMERO VARCHAR(20);

ALTER TABLE MEDICO
CHANGE NOME NOME_COMPLETO VARCHAR(50);