CREATE DATABASE OFICINA;
USE OFICINA;

CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE (
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL','RES','COM') NOT NULL,
    NUMERO VARCHAR(30) NOT NULL,
    ID_CLIENTE INT
);

CREATE TABLE MARCA (
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO (
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) NOT NULL,
    PLACA VARCHAR(30) NOT NULL UNIQUE,
    ID_MARCA INT
);

CREATE TABLE COR (
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR (
    ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY (ID_CARRO, ID_COR)
);


ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARROCOR_COR
FOREIGN KEY (ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARROCOR_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(IDCARRO);

--------- SELECTS ------------

SELECT 
    C.NOME, 
    T.TIPO, 
    T.NUMERO
FROM 
    CLIENTE C
JOIN 
    TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY 
    C.NOME;


SELECT 
    CAR.MODELO, 
    CAR.PLACA, 
    C.COR
FROM 
    CARRO CAR
JOIN 
    CARRO_COR CC ON CAR.IDCARRO = CC.ID_CARRO
JOIN 
    COR C ON CC.ID_COR = C.IDCOR;

SELECT 
    PLACA, 
    COUNT(*) AS QTD
FROM 
    CARRO
GROUP BY 
    PLACA
HAVING 
    COUNT(*) > 1;

SELECT 
    C.NOME AS CLIENTE,
    CA.MODELO AS CARRO,
    CA.PLACA,
    M.MARCA,
    CO.COR
FROM 
    CLIENTE C
JOIN 
    CARRO CA ON C.ID_CARRO = CA.IDCARRO
JOIN 
    MARCA M ON CA.ID_MARCA = M.IDMARCA
JOIN 
    CARRO_COR CC ON CA.IDCARRO = CC.ID_CARRO
JOIN 
    COR CO ON CC.ID_COR = CO.IDCOR;


--------- DELETES --------

DELETE FROM CLIENTE
WHERE IDCLIENTE NOT IN (
    SELECT DISTINCT ID_CLIENTE FROM TELEFONE
);

DELETE FROM TELEFONE
WHERE TIPO = 'COM';


------- ALTER TABLES -------

ALTER TABLE TELEFONE
MODIFY ID_CLIENTE INT NOT NULL;

ALTER TABLE TELEFONE
MODIFY NUMERO VARCHAR(15);
