CREATE DATABASE projeto2;
USE projeto2;

-- Corrigindo PESSOA
CREATE TABLE PESSOA(
    IDPESSOA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)
);

-- Corrigindo TIME
CREATE TABLE TIME(
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    NOMETIME VARCHAR(30),
    ID_PESSOA INT,
    FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
);

-- Corrigindo JOGADOR
CREATE TABLE JOGADOR(
    IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)
);

-- Corrigindo EQUIPE
CREATE TABLE EQUIPE(
    IDEQUIPE INT PRIMARY KEY AUTO_INCREMENT,
    NOMETIME VARCHAR(30),
    ID_JOGADOR INT,
    FOREIGN KEY(ID_JOGADOR) REFERENCES JOGADOR(IDJOGADOR)
);

-- Inserindo dados
INSERT INTO JOGADOR VALUES(NULL,'MESSI');
INSERT INTO EQUIPE VALUES(NULL,'INTER MIAMI',1);

INSERT INTO JOGADOR VALUES(NULL,'NEYMAR');
INSERT INTO EQUIPE VALUES(NULL,'SANTOS',2);

INSERT INTO JOGADOR VALUES(NULL,'CRISTIANO');
INSERT INTO EQUIPE VALUES(NULL,'AL NASSR',3);

INSERT INTO JOGADOR VALUES(NULL,'MBAPPE');
INSERT INTO EQUIPE VALUES(NULL,'REAL MADRID',4);


SELECT * FROM JOGADOR;

SELECT * FROM EQUIPE;

SELECT 
    J.NOME AS JOGADOR,
    E.NOMETIME AS EQUIPE
FROM 
    JOGADOR J
JOIN 
    EQUIPE E ON J.IDJOGADOR = E.ID_JOGADOR;

SELECT 
    J.NOME 
FROM 
    JOGADOR J
JOIN 
    EQUIPE E ON J.IDJOGADOR = E.ID_JOGADOR
WHERE 
    E.NOMETIME = 'SANTOS';

SELECT COUNT(*) AS TOTAL_JOGADORES FROM JOGADOR;

------ deletes -------------
DELETE FROM EQUIPE
WHERE ID_JOGADOR NOT IN (
    SELECT IDJOGADOR FROM JOGADOR
);

DELETE FROM PESSOA
WHERE IDPESSOA NOT IN (
    SELECT ID_PESSOA FROM TIME
);


------ ALTER TABLES --------
ALTER TABLE PESSOA
ADD FUNCAO VARCHAR(30);

ALTER TABLE TIME
MODIFY NOMETIME VARCHAR(50);


ALTER TABLE TIME
ADD ID_EQUIPE INT;

ALTER TABLE TIME
ADD CONSTRAINT FK_TIME_EQUIPE
FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(IDEQUIPE);
